"""Initial SwasthyaSync schema

Revision ID: 6b0c5b52ec64
Revises: 
Create Date: 2026-02-27 21:15:10.303165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c5b52ec64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('diet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_payload', sa.JSON(), nullable=False),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_requests_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_label', sa.String(length=64), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('ai_food_summary', sa.Text(), nullable=True),
    sa.Column('ai_guidance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_lifestyle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('breakfast_time', sa.Time(), nullable=True),
    sa.Column('lunch_time', sa.Time(), nullable=True),
    sa.Column('snack_time', sa.Time(), nullable=True),
    sa.Column('dinner_time', sa.Time(), nullable=True),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lifestyle')
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_logs_user_id'))

    op.drop_table('nutrition_logs')
    with op.batch_alter_table('diet_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_requests_user_id'))

    op.drop_table('diet_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
