"""store diet response payload

Revision ID: a0a4e8d2316f
Revises: 6b0c5b52ec64
Create Date: 2026-02-27 23:41:34.603666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a4e8d2316f'
down_revision = '6b0c5b52ec64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_payload', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_requests', schema=None) as batch_op:
        batch_op.drop_column('response_payload')

    # ### end Alembic commands ###
